try {
	console.log(num);
} catch (err) {
	console.log('A variavel n√£o existe');
}
